version: '3'

services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - ${DB_PORT}:3306
    command: --bind-address=db
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-pexample"
        ]
      interval: 5s
      retries: 10

  web:
    build: ./web
    volumes:
      - ./web:/app
      - ./init:/docker-entrypoint-initdb.d
    environment:
      DB_NAME: "${DB_NAME}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_HOST: "${DB_HOST}"
      DB_PORT: "${DB_PORT}"
      DB_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      SECRET_KEY: "${SECRET_KEY}"
      PRODUCTION: ${PRODUCTION}
    ports:
      - ${WEB_PORT}:8000
    depends_on:
      db:
        condition: service_healthy
        restart: true
    command: bash scripts/run.sh
    links:
      - db
