# Generated by Django 4.2.1 on 2023-05-28 11:09

from django.db import migrations


def add_librarian_group(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    librarian_group, created = Group.objects.get_or_create(name='Librarian')


class Migration(migrations.Migration):
    dependencies = []

    operations = [
        migrations.RunPython(add_librarian_group),
    ]
