# Generated by Django 4.2.1 on 2023-05-29 16:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("library_api", "0002_book_year"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="author",
        ),
        migrations.AddField(
            model_name="book",
            name="authors",
            field=models.ManyToManyField(related_name="books", to="library_api.author"),
        ),
        migrations.AddField(
            model_name="book",
            name="availability",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
