# Generated by Django 4.2.1 on 2023-05-30 11:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("library_api", "0003_remove_book_author_book_authors_book_availability"),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                height_field=1600,
                null=True,
                upload_to="covers",
                width_field=2560,
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="date_returned",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="loan",
            name="date_borrowed",
            field=models.DateField(auto_now_add=True),
        ),
    ]
