# Generated by Django 4.2.1 on 2023-05-30 16:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("library_api", "0005_alter_loan_cover_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="loan",
            name="cover_image",
        ),
        migrations.AddField(
            model_name="book",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                height_field=2560,
                null=True,
                upload_to="covers",
                width_field=1600,
            ),
        ),
    ]
