# Generated by Django 4.2.1 on 2023-05-31 07:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("library_api", "0006_remove_loan_cover_image_book_cover_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="loan",
            name="fine",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
