# Generated by Django 4.2.1 on 2023-05-31 08:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("library_api", "0007_book_price_loan_fine"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="price",
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
        ),
    ]
