# Generated by Django 4.2.1 on 2023-05-30 16:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("library_api", "0004_loan_cover_image_loan_date_returned_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loan",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                height_field=2560,
                null=True,
                upload_to="covers",
                width_field=1600,
            ),
        ),
    ]
