name: Django CI

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install Dependencies
      working-directory: api
      run: |
        python -m pip install --upgrade pipenv
        pipenv install
    - name: Run Tests
      working-directory: api
      run: |
        python manage.py test
