name: Django CI

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.10, 3.11]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      working-directory: ./api
      run: |
        python -m pip install --upgrade pipenv
        pipenv install
    - name: Run Tests
      working-directory: ./api
      run: |
        python manage.py test
