name: Django CI

on: [pull_request, push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - name: Read .env
      run: |
        cat .env
    - name: Install Dependencies
      working-directory: api
      run: |
        python -m pip install --upgrade pipenv
        pipenv install
    - name: Run Tests
      working-directory: api
      run: |
        pipenv run python manage.py test
